export const artistsData = [
  {
    id: "divine",
    artistName: "DIVINE",
    fullName: "Vivian Wilson Fernandes",
    birthDate: "1990-10-02",
    origin: "Mumbai, India",
    genres: ["Hip Hop", "Gully Rap", "Desi Hip Hop"],
    labels: [
      "Gully Gang Entertainment",
      "Sony Music India",
      "Mass Appeal India",
    ],
    yearsActive: "2011 to present",
    topTracks: ["Baazigar", "Mirchi", "Jungli Sher"],
    albums: [
      { title: "Kohinoor", year: 2019 },
      { title: "Punya Paap", year: 2020 },
      { title: "Gunehgar", year: 2022 },
    ],
    milestones: [
      "First Indian rapper on Spotify Times Square billboard",
      "Featured in Bollywood collaborations",
    ],
    coverPath: "covers/1.jpg",
  },

  {
    id: "krna",
    artistName: "KR$NA",
    fullName: "Krishna Kaul",
    birthDate: "1987-10-04",
    origin: "Delhi, India",
    genres: ["Hip Hop", "Desi Hip Hop"],
    labels: ["Universal", "Zee", "Kalamkaar"],
    yearsActive: "2006 to present",
    topTracks: ["Machayenge 4", "YKWIM", "No Losses"],
    albums: [],
    milestones: [
      "Early pioneer in Indian hip-hop",
      "Multiple collaborations with big names",
    ],
    coverPath: "covers/krna.jpg",
  },

  {
    id: "karan_aujla",
    artistName: "Karan Aujla",
    fullName: "Jaskaran Singh Aujla",
    birthDate: "1997-01-18",
    origin: "Ludhiana, Punjab, India",
    genres: ["Punjabi", "Hip Hop", "Pop", "R&B"],
    labels: ["Rehaan Records", "Warner Music India", "Speed Records"],
    yearsActive: "2014 to present",
    topTracks: ["Dont Worry", "Red Eyes", "Jhanjar", "Kya Baat Aa"],
    albums: [
      { title: "B.T.F.U.", year: 2021 },
      { title: "P-Pop Culture", year: 2025 },
    ],
    milestones: [
      "First song to chart UK Asian Chart: Dont Worry",
      "Major digital streams in Punjabi music",
    ],
    coverPath: "covers/karan_aujla.jpg",
  },

  {
    id: "the_weeknd",
    artistName: "The Weeknd",
    fullName: "Abel Makkonen Tesfaye",
    birthDate: "1990-02-16",
    origin: "Toronto, Ontario, Canada",
    genres: ["R&B", "Pop", "Alternative R&B"],
    labels: ["XO", "Republic Records"],
    yearsActive: "2009 to present",
    topTracks: [
      "Blinding Lights",
      "Starboy",
      "Earned It",
      "The Hills",
      "Cant Feel My Face",
    ],
    albums: [
      { title: "House of Balloons", year: 2011 },
      { title: "Beauty Behind the Madness", year: 2015 },
      { title: "After Hours", year: 2020 },
      { title: "Dawn FM", year: 2022 },
      { title: "Hurry Up Tomorrow", year: 2025 },
    ],
    milestones: [
      "Multiple Grammy Awards",
      "Global chart-topping hits",
      "Massive influence on modern R&B",
    ],
    coverPath: "covers/the_weeknd.jpg",
  },

  {
    id: "dhanda_nyoliwala",
    artistName: "Dhanda Nyoliwala",
    fullName: "",
    birthDate: null,
    origin: "Punjab / Haryanvi region",
    genres: ["Desi Hip Hop", "Punjabi", "Haryanvi"],
    labels: [],
    yearsActive: "Recent (2020s)",
    topTracks: ["Russian Bandana", "La La La", "Surrey BC"],
    albums: [],
    milestones: ["Back-to-back chartbusters", "Rising regional rap style"],
    coverPath: "covers/dhanda_nyoliwala.jpg",
  },
  {
    id: "sidhu_moose_wala",
    artistName: "Sidhu Moose Wala",
    fullName: "Shubhdeep Singh Sidhu",
    birthDate: "1993-06-11",
    deathDate: "2022-05-29",
    origin: "Moosa, Mansa, Punjab, India",
    genres: ["Punjabi Hip Hop", "Punjabi Pop", "Desi Hip Hop"],
    labels: ["5911 Records", "T-Series"],
    yearsActive: "2016 to 2022",
    topTracks: ["So High", "47", "The Last Ride", "295", "Mera Na"],
    albums: [
      { title: "PBX 1", year: 2018 },
      { title: "Snitches Get Stitches", year: 2020 },
      { title: "Moosetape", year: 2021 },
    ],
    milestones: [
      "Debut album PBX 1 charted on Canada Albums chart",
      "Released over 50+ singles",
      "Posthumous release 'Mera Na' charted internationally",
    ],
    coverPath: "covers/sidhu_moose_wala.jpg",
  },
];
